name: 'Update Analyzer'
description: 'Updates the version of a specified analyzer in SonarQube or SonarCloud and creates a pull request.'
author: 'SonarSource'

inputs:
  version:
    description: 'The new version to set for the analyzer (e.g., 1.12.0.12345).'
    required: true
  ticket:
    description: 'The Jira ticket number (e.g., SONAR-12345 or SC-12345). This determines the target product.'
    required: true
  plugin_language:
    description: 'The language key of the plugin to update (e.g., architecture, java, csharp).'
    required: true
  secret_name:
    description: 'Name of the secret to fetch from the vault that has access to the target repository.'
    required: true
  plugin_names:
    description: 'Comma-separated list of plugin names to update instead of plugin_language.'
    required: false
  base_branch:
    description: 'The base branch for the product pull request.'
    required: false
    default: 'master'
  draft:
    description: 'A boolean value to control if the pull request is created as a draft.'
    required: false
    default: 'false'
  reviewers:
    description: 'A comma-separated list of GitHub usernames to request a review from.'
    required: false
  pr_body:
    description: 'The body of the pull request.'
    required: false

outputs:
  pr-url:
    description: 'The URL of the created pull request.'
    value: ${{ steps.create_pr.outputs.pull-request-url }}

runs:
  using: 'composite'
  steps:
    - name: Get GitHub token from Vault
      id: secrets
      uses: SonarSource/vault-action-wrapper@v3
      with:
        secrets: |
          development/github/token/SonarSource-${{ inputs.secret_name }} token | GITHUB_TOKEN;

    - name: Set up environment
      id: setup_env
      shell: bash
      run: |
        if [[ "${{ inputs.ticket }}" == SONAR-* ]]; then
          echo "PRODUCT_REPOSITORY=sonar-enterprise" >> $GITHUB_ENV
          echo "BUILD_GRADLE_FILE=build.gradle" >> $GITHUB_ENV
        elif [[ "${{ inputs.ticket }}" == SC-* ]]; then
          echo "PRODUCT_REPOSITORY=sonarcloud-core" >> $GITHUB_ENV
          echo "BUILD_GRADLE_FILE=private/edition-sonarcloud/build.gradle" >> $GITHUB_ENV
        else
          echo "::error::Invalid ticket format. Must start with SONAR- or SC-."
          exit 1
        fi

    - name: Checkout target repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: SonarSource/${{ env.PRODUCT_REPOSITORY }}
        ref: ${{ inputs.base_branch }}
        sparse-checkout: ${{ env.BUILD_GRADLE_FILE }}
        sparse-checkout-cone-mode: false
        fetch-depth: 0
        token: ${{ fromJSON(steps.secrets.outputs.vault).GITHUB_TOKEN }}

    - name: Update analyzer version in build file
      shell: bash
      run: |
        set -euo pipefail
        # Prepare the list of plugins to update
        if [[ -n "${{ inputs.plugin_names }}" ]]; then
          echo "Using plugin_names: ${{ inputs.plugin_names }}"
          IFS=',' read -ra PLUGINS <<< "${{ inputs.plugin_names }}"
        else
          echo "Using plugin_language: ${{ inputs.plugin_language }}"
          PLUGINS=("${{ inputs.plugin_language }}")
        fi
        
        # Update each plugin
        for plugin in "${PLUGINS[@]}"; do
          plugin=$(echo "$plugin" | xargs)
          echo "Updating analyzer version in ${{ env.BUILD_GRADLE_FILE }} for plugin $plugin"
          sed -i "s/\(:sonar-$plugin.*-plugin:\)[0-9.]*/\1${{ inputs.version }}/g" ${{ env.BUILD_GRADLE_FILE }}
        done
        
        echo "Showing diff:"
        git --no-pager diff ${{ env.BUILD_GRADLE_FILE }}

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
      with:
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        commit-message: '${{ inputs.ticket }} Update `${{ inputs.plugin_language }}` plugins to version ${{ inputs.version }}'
        title: '${{ inputs.ticket }} Update `${{ inputs.plugin_language }}` to version ${{ inputs.version }}'
        body: ${{ inputs.pr_body }}
        base: ${{ inputs.base_branch }}
        branch: '${{ inputs.plugin_language }}/update-analyzer-${{ inputs.version }}'
        token: ${{ fromJSON(steps.secrets.outputs.vault).GITHUB_TOKEN }}
        draft: ${{ inputs.draft }}
        reviewers: ${{ inputs.reviewers }}
