name: 'Create Jira Release Ticket'
description: 'Creates a Jira release ticket.'
author: 'SonarSource'

inputs:
  jira_user:
    description: 'Jira user for authentication'
    required: true
  jira_token:
    description: 'Jira API token for authentication'
    required: true
  project_key:
    description: 'The key of the project (e.g., SONARIAC)'
    required: true
  project_name:
    description: 'The display name of the project (e.g., SonarIaC)'
    required: true
  version:
    description: 'The version being released (e.g., 11.44.2)'
    required: true
  short_description:
    description: 'A short description for the release'
    required: true
  targeted_product:
    description: 'The targeted product version (e.g., 11.0)'
    required: true
  sq_compatibility:
    description: 'SonarQube compatibility version (e.g., 2025.3)'
    required: true
  use_sandbox:
    description: 'Use the sandbox server instead of the production Jira'
    required: false
    default: 'True'
  documentation_status:
    description: 'Status of the documentation'
    required: false
    default: 'N/A'
  rule_props_changed:
    description: 'Whether rule properties have changed'
    required: false
    default: 'No'

outputs:
  ticket_key:
    description: 'The key of the created Jira ticket (e.g., REL-123)'
    value: ${{ steps.run_python_script.outputs.ticket_key }}

runs:
  using: "composite"
  steps:
    - name: Set Action Ref
      shell: bash
      run: echo "ACTION_REF=${{ github.action_ref }}" >> $GITHUB_ENV

    - name: Checkout Action Repository
      uses: actions/checkout@v4
      with:
        repository: SonarSource/release-github-actions
        ref: ${{ env.ACTION_REF }}
        path: '.action-repo'
        sparse-checkout: |
          tools

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      shell: bash
      run: pip install -r .action-repo/tools/requirements.txt

    - name: Run Python Script to Create Ticket
      id: run_python_script
      shell: bash
      run: |
        TICKET_KEY=$(python .action-repo/tools/create_release_ticket.py \
          --project-key="${{ inputs.project_key }}" \
          --project-name="${{ inputs.project_name }}" \
          --version="${{ inputs.version }}" \
          --short-description="${{ inputs.short_description }}" \
          --targeted-product="${{ inputs.targeted_product }}" \
          --sq-compatibility="${{ inputs.sq_compatibility }}" \
          --use-sandbox="${{ inputs.use_sandbox }}" \
          --documentation-status="${{ inputs.documentation_status }}" \
          --rule-props-changed="${{ inputs.rule_props_changed }}"
        )
        echo "ticket_key=${TICKET_KEY}" >> $GITHUB_OUTPUT
      env:
        JIRA_USER: ${{ inputs.jira_user }}
        JIRA_TOKEN: ${{ inputs.jira_token }}
