name: 'Get Jira Release Notes'
description: 'Fetches Jira release notes and generates the release notes URL for a given project and version.'
author: 'SonarSource'

inputs:
  jira-project-key:
    description: 'The key of the Jira project (e.g., SONARIAC). Can also be set via JIRA_PROJECT_KEY environment variable.'
  jira-version-name:
    description: 'The name of the Jira version/fixVersion (e.g., 1.2.3). Can also be set via JIRA_VERSION_NAME environment variable.'
  use-jira-sandbox:
    description: "Use the sandbox Jira server instead of production."
  issue-types:
    description: 'Optional comma-separated list of issue types to include, in order.'
    default: 'Feature,False Positive,False Negative,Bug'

outputs:
  release-notes:
    description: 'The formatted release notes as Markdown.'
    value: ${{ steps.get_notes.outputs.release-notes }}
  jira-release-notes:
    description: 'The formatted release notes in Jira wiki markup format.'
    value: ${{ steps.get_notes.outputs.jira-release-notes }}
  jira-release-url:
    description: 'The URL to the Jira release notes page.'
    value: ${{ steps.get_notes.outputs.jira-release-url }}
  jira-release-issue-filter-url:
    description: 'The URL of the issue filter for the Jira release.'
    value: ${{ steps.get_notes.outputs.jira-release-issue-filter-url }}

runs:
  using: "composite"
  steps:
    - name: Get Jira Credentials from Vault
      id: secrets
      uses: SonarSource/vault-action-wrapper@v3
      with:
        secrets: |
          development/kv/data/jira user | JIRA_USER;
          development/kv/data/jira token | JIRA_TOKEN;

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Get JIRA_VERSION_NAME if not provided
      if: ${{ !inputs.jira-version-name && !env.JIRA_VERSION_NAME }}
      uses: SonarSource/release-github-actions/get-jira-version@v1

    - name: Get Jira release notes and URL
      id: get_notes
      shell: bash
      env:
        JIRA_USER: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_USER }}
        JIRA_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_TOKEN }}
        ISSUE_TYPES: ${{ inputs.issue-types }}
        JIRA_URL: "https://sonarsource${{ ((inputs.use-jira-sandbox || env.USE_JIRA_SANDBOX) == 'true') && '-sandbox-608' || '' }}.atlassian.net/"
      run: |
        PROJECT_KEY="${{ inputs.jira-project-key || env.JIRA_PROJECT_KEY }}"
        VERSION_NAME="${{ inputs.jira-version-name || env.JIRA_VERSION_NAME }}"
        
        if [[ -z "$PROJECT_KEY" || -z "$VERSION_NAME" ]]; then
          echo "::error::Both jira-project-key and jira-version-name must be provided"
          exit 1
        fi
        
        python ${{ github.action_path }}/get_jira_release_notes.py \
          --project-key="$PROJECT_KEY" \
          --version-name="$VERSION_NAME" \
          --issue-types="$ISSUE_TYPES" \
          --jira-url="$JIRA_URL" \
          | tee -a $GITHUB_OUTPUT | sed 's/^jira-release-url=/JIRA_RELEASE_URL=/' | sed 's/^jira-release-issue-filter-url=/JIRA_RELEASE_ISSUE_FILTER_URL=/' | sed 's/^release-notes<</RELEASE_NOTES<</' | sed 's/^jira-release-notes<</JIRA_RELEASE_NOTES<</' >> $GITHUB_ENV
