name: Bump Project Version

inputs:
  version:
    description: The new version (without -SNAPSHOT)
    required: true
  token:
    description: The GitHub token for PR creation
    required: false
  excluded-modules:
    description: A comma-separated list of modules to exclude from version bumping
    required: false
  base-branch:
    description: The base branch for the pull request
    required: false
    default: master
  pr-labels:
    description: Comma-separated list of labels to add to the pull request
    required: false

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
  - name: Bump version
    shell: bash
    env:
      VERSION: "${{ inputs.version }}-SNAPSHOT"
      EXCLUDED_MODULES: ${{ inputs.excluded-modules || '' }}
    run: |
      bash "${GITHUB_ACTION_PATH}/bump_version.sh"
  - name: Create Pull Request for Version Bump
    uses: SonarSource/release-github-actions/create-pull-request@v1
    id: create-pr
    env:
      TITLE_MESSAGE: Prepare next development iteration ${{ inputs.version }}
    with:
      token: ${{ inputs.token }}
      author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      commit-message: ${{ env.TITLE_MESSAGE }}
      title: ${{ env.TITLE_MESSAGE }}
      base: ${{ inputs.base-branch }}
      branch: bot/prepare-next-development-iteration-${{ inputs.version }}
      labels: ${{ inputs.pr-labels }}
      reviewers: ${{ github.actor }}

outputs:
  pull-request-url:
    description: URL of the version bump pull request
    value: ${{ steps.create-pr.outputs.pull-request-url }}
