name: Bump Project Version

inputs:
  version:
    description: The new version (without -SNAPSHOT)
    required: true
  secret-name:
    description: The name of the GitHub token secret in Vault for PR creation
    required: true
  excluded-modules:
    description: A comma-separated list of modules to exclude from version bumping
    required: false

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
  - name: Bump version
    shell: bash
    env:
      VERSION: "${{ inputs.version }}-SNAPSHOT"
      EXCLUDED_MODULES: ${{ inputs.excluded-modules || '' }}
    run: |
      bash "${GITHUB_ACTION_PATH}/bump_version.sh"
  - name: Get GitHub token from Vault
    id: secrets
    uses: SonarSource/vault-action-wrapper@v3
    with:
      secrets: |
        development/github/token/SonarSource-${{ inputs.secret-name}} token | GITHUB_TOKEN;
  - name: Create Pull Request for Version Bump
    uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
    id: create-pr
    env:
      TITLE_MESSAGE: Prepare next development iteration ${{ inputs.version }}
    with:
      author: ${{ github.actor }} <${{ github.actor }}>
      commit-message: ${{ env.TITLE_MESSAGE }}
      title: ${{ env.TITLE_MESSAGE }}
      base: master
      branch: bot/prepare-next-development-iteration-${{ inputs.version }}
      labels: skip-qa
      reviewers: ${{ github.actor }}
      token: ${{ fromJSON(steps.secrets.outputs.vault).GITHUB_TOKEN }}

outputs:
  pull-request-url:
    description: URL of the version bump pull request
    value: ${{ steps.create-pr.outputs.pull-request-url }}
