name: 'Release Jira Version'
description: 'Releases a specified Jira version and creates a new one.'
author: 'SonarSource'

inputs:
  jira_project_key:
    description: 'The key of the Jira project (e.g., SONARIAC).'
    required: true
  jira_version_name:
    description: |
      The name of the Jira version to release (e.g., 1.2.3).
      If not provided, the script will determine the next version based on the Jira version.'
    required: false
  use_jira_sandbox:
    description: "Use the sandbox Jira server instead of production."
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Get Jira Credentials from Vault
      id: secrets
      uses: SonarSource/vault-action-wrapper@v3
      with:
        secrets: |
          development/kv/data/jira user | JIRA_USER;
          development/kv/data/jira token | JIRA_TOKEN;

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - uses: SonarSource/release-github-actions/get-jira-version@9fcdc700a2046505f6ebeed43be2176569910084
      if: ${{ !inputs.jira_version_name }}

    - name: Determine Jira Version
      id: determine_version_name
      if: ${{ !inputs.jira_version_name }}
      shell: bash
      run: |
        echo "VERSION_NAME=$(echo "${{ steps.get-jira-version.outputs.jira_version }}" | awk -F. '{$NF+=1; OFS="."; print $0}')" >> $GITHUB_OUTPUT

    - name: Release Jira Version
      id: run_python_script
      shell: bash
      env:
        JIRA_USER: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_USER }}
        JIRA_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_TOKEN }}
        JIRA_PROD_URL: "https://sonarsource.atlassian.net/"
        JIRA_SANDBOX_URL: "https://sonarsource-sandbox-608.atlassian.net/"
      run: |
        python ${{ github.action_path }}/release_jira_version.py \
        --project-key="${{ inputs.jira_project_key }}" \
        --version-name="${{ inputs.jira_version_name || steps.determine_version_name.outputs.VERSION_NAME }}" \
        --jira-url="${{ ((inputs.use_jira_sandbox || env.USE_JIRA_SANDBOX) == 'true') && env.JIRA_SANDBOX_URL || env.JIRA_PROD_URL }}" \
        >> $GITHUB_OUTPUT
