name: 'Update Release ticket Status'
description: 'Updates the status of a Jira release ticket and can change its assignee.'
author: 'SonarSource'

inputs:
  release-ticket-key:
    description: 'The key of the Jira ticket to update (e.g., REL-1234).'
    required: true
  status:
    description: 'The target status for the ticket. Must be a valid transition.'
    required: true
  assignee:
    description: 'The email of the user to assign the ticket to.'
    required: false
    default: ''
  use-jira-sandbox:
    description: 'Use the sandbox server instead of the production Jira. Can also be controlled via USE_JIRA_SANDBOX environment variable.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Get Jira Credentials from Vault
      id: secrets
      uses: SonarSource/vault-action-wrapper@v3
      with:
        secrets: |
          development/kv/data/jira user | JIRA_USER;
          development/kv/data/jira token | JIRA_TOKEN;

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run Python Script to Update Ticket
      id: run_python_script
      shell: bash
      env:
        JIRA_USER: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_USER }}
        JIRA_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_TOKEN }}
        JIRA_PROD_URL: "https://sonarsource.atlassian.net/"
        JIRA_SANDBOX_URL: "https://sonarsource-sandbox-608.atlassian.net/"
        ASSIGNEE_INPUT: ${{ inputs.assignee }}
        TICKET_KEY: ${{ inputs.release-ticket-key }}
        STATUS: ${{ inputs.status }}
        JIRA_URL: ${{ ((inputs.use-jira-sandbox || env.USE_JIRA_SANDBOX) == 'true') && env.JIRA_SANDBOX_URL || env.JIRA_PROD_URL }}
      run: |
        ASSIGNEE_FLAG=""
        if [[ -n "$ASSIGNEE_INPUT" ]]; then
          ASSIGNEE_FLAG="--assignee=$ASSIGNEE_INPUT"
        fi

        python ${{ github.action_path }}/update_release_ticket.py \
          --ticket-key="$TICKET_KEY" \
          --status="$STATUS" \
          ${ASSIGNEE_FLAG} \
          --jira-url="$JIRA_URL"
