name: 'Create Integration Ticket'
description: 'Creates a Jira integration ticket with a custom summary and links it to another ticket.'
author: 'SonarSource'

inputs:
  target-jira-project:
    description: 'The key of the project where the ticket will be created (e.g., SQS)'
    required: true
  release-ticket-key:
    description: 'The key of the release ticket to link to (e.g., REL-123)'
    required: true
  ticket-summary:
    description: 'The summary/title for the integration ticket'
  ticket-description:
    description: 'Description for the integration ticket'
  plugin-name:
    description: 'The name of the plugin (used to generate ticket summary if ticket-summary is not provided)'
  release-version:
    description: 'The release version (used to generate ticket summary if ticket-summary is not provided)'
  use-jira-sandbox:
    description: "Use the sandbox server instead of the production Jira."
  link-type:
    description: 'The type of link to create (e.g., "relates to", "depends on")'
    default: 'relates to'

outputs:
  ticket-key:
    description: 'The key of the created Jira ticket (e.g., SQS-123)'
    value: ${{ steps.run_python_script.outputs.ticket_key }}
  ticket-url:
    description: 'The URL of the created Jira ticket.'
    value: ${{ steps.run_python_script.outputs.ticket_url }}

runs:
  using: 'composite'
  steps:
    - name: Get Jira Credentials from Vault
      id: secrets
      uses: SonarSource/vault-action-wrapper@320bd31b03e5dacaac6be51bbbb15adf7caccc32 # v3.1
      with:
        secrets: |
          development/kv/data/jira user | JIRA_USER;
          development/kv/data/jira token | JIRA_TOKEN;

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - uses: SonarSource/release-github-actions/get-release-version@f450c1d5ec393371788f0ad9c889a82358da2b5e
      if: ${{ !inputs.ticket-summary && !inputs.release-version && !env.RELEASE_VERSION }}

    - name: Validate inputs and generate ticket summary
      id: validate_inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.ticket-summary }}" ]; then
          if [ -z "${{ inputs.plugin-name }}" ] || [ -z "${{ inputs.release-version || env.RELEASE_VERSION }}" ]; then
            echo "Error: Either ticket-summary must be provided, or both plugin-name and release-version must be provided."
            exit 1
          fi
          GENERATED_SUMMARY="Update ${{ inputs.plugin-name }} to ${{ inputs.release-version || env.RELEASE_VERSION }}"
          echo "Generated ticket summary: $GENERATED_SUMMARY"
          echo "ticket_summary=$GENERATED_SUMMARY" >> $GITHUB_OUTPUT
        else
          echo "ticket_summary=${{ inputs.ticket-summary }}" >> $GITHUB_OUTPUT
        fi

    - name: Run Python script
      id: run_python_script
      shell: bash
      env:
        JIRA_USER: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_USER }}
        JIRA_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_TOKEN }}
        JIRA_PROD_URL: "https://sonarsource.atlassian.net/"
        JIRA_SANDBOX_URL: "https://sonarsource-sandbox-608.atlassian.net/"
        TICKET_DESCRIPTION: ${{ inputs.ticket-description }}
      run: |
        python ${{ github.action_path }}/create_integration_ticket.py \
          --ticket-summary "${{ steps.validate_inputs.outputs.ticket_summary }}" \
          --target-jira-project "${{ inputs.target-jira-project }}" \
          --release-ticket-key "${{ inputs.release-ticket-key }}" \
          --jira-url="${{ ((inputs.use-jira-sandbox || env.USE_JIRA_SANDBOX) == 'true') && env.JIRA_SANDBOX_URL || env.JIRA_PROD_URL }}" \
          --link-type "${{ inputs.link-type }}" \
          ${TICKET_DESCRIPTION:+--ticket-description "$TICKET_DESCRIPTION"} >> $GITHUB_OUTPUT
