name: 'Check releasability status'
description: 'Checks the Releasability Status on the specified branch'
author: 'SonarSource'

inputs:
  github-token:
    description: 'The GitHub token for API calls.'
    required: true
    default: ${{ github.token }}
  branch:
    description: 'The branch from which to check the releasability status.'
    required: false
    default: 'master'
  with-optional-checks:
    description: 'Whether to also check that the description does not contain "failed optional checks".'
    required: false
    default: 'true'

outputs:
  releasability-state:
    description: 'The state of the Releasability status (e.g., success, failure, pending)'
    value: ${{ steps.check.outputs.releasability-state }}
  releasability-description:
    description: 'The description of the Releasability status'
    value: ${{ steps.check.outputs.releasability-description }}

runs:
  using: 'composite'
  steps:
    - name: Check releasability status
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        BRANCH_NAME: ${{ inputs.branch }}
        WITH_OPTIONAL_CHECKS: ${{ inputs.with-optional-checks }}
      run: |
        echo "Checking Releasability status on $BRANCH_NAME branch..."

        # Get the status for the specified branch
        STATUS_RESPONSE=$(gh api "/repos/${{ github.repository }}/commits/$BRANCH_NAME/status" 2>/dev/null)

        if [ $? -ne 0 ]; then
          echo "❌ Failed to get status information for $BRANCH_NAME branch"
          exit 1
        fi

        # Find the Releasability status
        RELEASABILITY_STATE=$(echo "$STATUS_RESPONSE" | jq -r '.statuses[] | select(.context == "Releasability") | .state')
        RELEASABILITY_DESCRIPTION=$(echo "$STATUS_RESPONSE" | jq -r '.statuses[] | select(.context == "Releasability") | .description')

        # Output the state and description for use in subsequent steps
        echo "releasability-state=$RELEASABILITY_STATE" >> $GITHUB_OUTPUT
        echo "releasability-description=$RELEASABILITY_DESCRIPTION" >> $GITHUB_OUTPUT

        if [ -z "$RELEASABILITY_STATE" ] || [ "$RELEASABILITY_STATE" = "null" ]; then
          echo "❌ Could not find Releasability status on $BRANCH_NAME branch"
          exit 1
        fi

        echo "Found Releasability status: $RELEASABILITY_STATE"
        echo "Description: $RELEASABILITY_DESCRIPTION"

        # Check if state is success
        if [ "$RELEASABILITY_STATE" != "success" ]; then
          echo "❌ Releasability status is not success: $RELEASABILITY_STATE"
          exit 1
        fi

        # Check optional failures if requested
        if [ "$WITH_OPTIONAL_CHECKS" = "true" ]; then
          if echo "$RELEASABILITY_DESCRIPTION" | grep -i "failed optional checks" > /dev/null; then
            echo "❌ Releasability status contains 'failed optional checks' in description"
            exit 1
          fi
        fi

        echo "✅ Releasability status check passed"
