name: 'Check releasability status'
description: 'Checks the Releasability Status on the master branch'
author: 'SonarSource'

inputs:
  github-token:
    description: 'The GitHub token for API calls.'
    required: true
    default: ${{ github.token }}
  with-optional-checks:
    description: 'Whether to also check that the description does not contain "failed optional checks".'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Check releasability status
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "Checking Releasability status on master branch..."
        
        # Get the status for the master branch
        STATUS_RESPONSE=$(gh api "/repos/${{ github.repository }}/commits/master/status" 2>/dev/null)
        
        if [ $? -ne 0 ]; then
          echo "❌ Failed to get status information for master branch"
          exit 1
        fi
        
        # Find the Releasability status
        RELEASABILITY_STATE=$(echo "$STATUS_RESPONSE" | jq -r '.statuses[] | select(.context == "Releasability") | .state')
        RELEASABILITY_DESCRIPTION=$(echo "$STATUS_RESPONSE" | jq -r '.statuses[] | select(.context == "Releasability") | .description')
        
        if [ -z "$RELEASABILITY_STATE" ] || [ "$RELEASABILITY_STATE" = "null" ]; then
          echo "❌ Could not find Releasability status on master branch"
          exit 1
        fi
        
        echo "Found Releasability status: $RELEASABILITY_STATE"
        echo "Description: $RELEASABILITY_DESCRIPTION"
        
        # Check if state is success
        if [ "$RELEASABILITY_STATE" != "success" ]; then
          echo "❌ Releasability status is not success: $RELEASABILITY_STATE"
          exit 1
        fi
        
        # Check optional failures if requested
        if [ "${{ inputs.with-optional-checks }}" = "true" ]; then
          if echo "$RELEASABILITY_DESCRIPTION" | grep -i "failed optional checks" > /dev/null; then
            echo "❌ Releasability status contains 'failed optional checks' in description"
            exit 1
          fi
        fi
        
        echo "✅ Releasability status check passed"
