name: 'Create Jira Release Ticket'
description: 'Creates a Jira release ticket.'
author: 'SonarSource'

inputs:
  project-name:
    description: 'The display name of the project (e.g., SonarIaC)'
    required: true
  short-description:
    description: 'A short description for the release'
    required: true
  jira-project-key:
    description: 'The key of the project (e.g., SONARIAC). Required if JIRA_PROJECT_KEY env var is not set.'
  version:
    description: 'The version being released (e.g., 11.44.2), or leave empty to use the release version.'
  due-date:
    description: 'Due date of the release.'
  use-jira-sandbox:
    description: "Use the sandbox server instead of the production Jira."
  documentation-status:
    description: 'Status of the documentation'
    default: 'N/A'
  rule-props-changed:
    description: 'Whether rule properties have changed'
    default: 'No'
  jira-release-url:
    description: 'The URL to the Jira release notes page. Required if JIRA_RELEASE_URL env var is not set.'
  sonarlint-changelog:
    description: 'The SonarLint changelog content.'
    default: ''
  start-progress:
    description: 'Whether to start progress on the release ticket.'

outputs:
  release-ticket-key:
    description: 'The key of the created Jira ticket (e.g., REL-123)'
    value: ${{ steps.run_python_script.outputs.ticket_key }}
  release-ticket-url:
    description: 'The URL of the created Jira ticket.'
    value: ${{ steps.run_python_script.outputs.ticket_url }}

runs:
  using: "composite"
  steps:
    - name: Get Jira Credentials from Vault
      id: secrets
      uses: SonarSource/vault-action-wrapper@v3
      with:
        secrets: |
          development/kv/data/jira user | JIRA_USER;
          development/kv/data/jira token | JIRA_TOKEN;

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - uses: SonarSource/release-github-actions/get-release-version@v1
      if: ${{ !inputs.version }}

    - name: Get Jira Release Notes URL
      if: ${{ !inputs.jira-release-url && !env.JIRA_RELEASE_URL }}
      uses: SonarSource/release-github-actions/get-jira-release-notes@v1
      with:
        jira-project-key: ${{ inputs.jira-project-key }}
        use-jira-sandbox: ${{ inputs.use-jira-sandbox }}

    - name: Run Python Script to Create Ticket
      id: run_python_script
      shell: bash
      env:
        JIRA_USER: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_USER }}
        JIRA_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_TOKEN }}
        PROJECT_NAME: ${{ inputs.project-name }}
        RELEASE_VERSION: ${{ inputs.version || env.RELEASE_VERSION }}
        SHORT_DESCRIPTION: ${{ inputs.short-description }}
        DUE_DATE: ${{ inputs.due-date }}
        JIRA_URL: ${{ ((inputs.use-jira-sandbox || env.USE_JIRA_SANDBOX) == 'true') && 'https://sonarsource-sandbox-608.atlassian.net/' || 'https://sonarsource.atlassian.net/' }}
        DOCUMENTATION_STATUS: ${{ inputs.documentation-status }}
        RULE_PROPS_CHANGED: ${{ inputs.rule-props-changed }}
        JIRA_RELEASE_URL: ${{ inputs.jira-release-url || env.JIRA_RELEASE_URL }}
        SONARLINT_CHANGELOG: ${{ inputs.sonarlint-changelog }}
      run: |
        PROJECT_KEY="${{ inputs.jira-project-key || env.JIRA_PROJECT_KEY }}"
        
        if [[ -z "$PROJECT_KEY" ]]; then
          echo "::error::Both jira-project-key input and JIRA_PROJECT_KEY environment variable are missing. One must be provided."
          exit 1
        fi

        python ${{ github.action_path }}/create_release_ticket.py \
          --project-key="$PROJECT_KEY" \
          --project-name="$PROJECT_NAME" \
          --version="$RELEASE_VERSION" \
          --due-date="$DUE_DATE" \
          --short-description="$SHORT_DESCRIPTION" \
          --jira-url="$JIRA_URL" \
          --documentation-status="$DOCUMENTATION_STATUS" \
          --rule-props-changed="$RULE_PROPS_CHANGED" \
          --jira-release-url="$JIRA_RELEASE_URL" \
          --sonarlint-changelog="$SONARLINT_CHANGELOG" >> $GITHUB_OUTPUT

    - name: Start Progress on Release Ticket
      if: ${{ inputs.start-progress == 'true' }}
      uses: SonarSource/release-github-actions/update-release-ticket-status@v1
      with:
        release-ticket-key: ${{ steps.run_python_script.outputs.ticket_key }}
        status: "Start Progress"

    - name: Set Env Variables
      shell: bash
      run: |
        echo "RELEASE_TICKET_KEY=${{ steps.run_python_script.outputs.ticket_key }}" >> $GITHUB_ENV
        echo "RELEASE_TICKET_URL=${{ steps.run_python_script.outputs.ticket_url }}" >> $GITHUB_ENV
