name: 'Create Jira Release Ticket'
description: 'Creates a Jira release ticket.'
author: 'SonarSource'

inputs:
  project_key:
    description: 'The key of the project (e.g., SONARIAC)'
    required: true
  project_name:
    description: 'The display name of the project (e.g., SonarIaC)'
    required: true
  version:
    description: 'The version being released (e.g., 11.44.2)'
    required: true
  short_description:
    description: 'A short description for the release'
    required: true
  targeted_product:
    description: 'The targeted product version (e.g., 11.0)'
    required: false
  sq_compatibility:
    description: 'SonarQube compatibility version (e.g., 2025.3)'
    required: true
  use_sandbox:
    description: "Use the sandbox server instead of the production Jira."
    required: false
    default: 'true'
  documentation_status:
    description: 'Status of the documentation'
    required: false
    default: 'N/A'
  rule_props_changed:
    description: 'Whether rule properties have changed'
    required: false
    default: 'No'
  jira_release_name:
    description: 'The specific Jira release version to use.'
    required: false
    default: ''
  sonarlint_changelog:
    description: 'The SonarLint changelog content.'
    required: false
    default: ''

outputs:
  ticket_key:
    description: 'The key of the created Jira ticket (e.g., REL-123)'
    value: ${{ steps.run_python_script.outputs.ticket_key }}
  jira_release_name:
    description: 'The name of the Jira release found or used by the script.'
    value: ${{ steps.run_python_script.outputs.jira_release_name }}
  ticket_url:
    description: 'The URL of the created Jira ticket.'
    value: ${{ steps.run_python_script.outputs.ticket_url }}
  release_url:
    description: 'The URL of the Jira release page.'
    value: ${{ steps.run_python_script.outputs.release_url }}

runs:
  using: "composite"
  steps:
    - name: Get Jira Credentials from Vault
      id: secrets
      uses: SonarSource/vault-action-wrapper@v3
      with:
        secrets: |
          development/kv/data/jira user | JIRA_USER;
          development/kv/data/jira token | JIRA_TOKEN;

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.8'

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run Python Script to Create Ticket
      id: run_python_script
      shell: bash
      run: |
        SANDBOX_FLAG=""
        if [[ "${{ inputs.use_sandbox }}" == "true" ]]; then
          SANDBOX_FLAG="--use-sandbox"
        fi

        python ${{ github.action_path }}/create_release_ticket.py \
          --project-key="${{ inputs.project_key }}" \
          --project-name="${{ inputs.project_name }}" \
          --version="${{ inputs.version }}" \
          --short-description="${{ inputs.short_description }}" \
          --targeted-product="${{ inputs.targeted_product }}" \
          --sq-compatibility="${{ inputs.sq_compatibility }}" \
          ${SANDBOX_FLAG} \
          --documentation-status="${{ inputs.documentation_status }}" \
          --rule-props-changed="${{ inputs.rule_props_changed }}" \
          --jira-release-name="${{ inputs.jira_release_name }}" \
          --sonarlint-changelog="${{ inputs.sonarlint_changelog }}" >> $GITHUB_OUTPUT
      env:
        JIRA_USER: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_USER }}
        JIRA_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).JIRA_TOKEN }}

    - name: Set Env Variables
      shell: bash
      run: |
        echo "JIRA_RELEASE_NAME=${{ steps.run_python_script.outputs.jira_release_name }}" >> $GITHUB_ENV
        echo "JIRA_RELEASE_URL=${{ steps.run_python_script.outputs.release_url }}" >> $GITHUB_ENV
        echo "RELEASE_TICKET_KEY=${{ steps.run_python_script.outputs.ticket_key }}" >> $GITHUB_ENV
        echo "RELEASE_TICKET_URL=${{ steps.run_python_script.outputs.ticket_url }}" >> $GITHUB_ENV
