name: Get Jira Version

description: Get jira version from the release version.

outputs:
  jira-version-name:
    description: 'The Jira version derived from the release version.'
    value: ${{ steps.get_version.outputs.jira-version-name }}

runs:
    using: "composite"
    steps:
      - uses: SonarSource/release-github-actions/get-release-version@8246a186b64accacf764b3bc891a0f8079c002ea
        if: ${{ !env.RELEASE_VERSION }}
      - name: Get jira version from release version
        id: get_version
        shell: bash
        run: |
          # Extract everything up to the third dot (major.minor.patch)
          VERSION=$(echo "$RELEASE_VERSION" | cut -d '.' -f 1-3)
          
          # Remove trailing '.0' if it exists (to match Jira version format)
          JIRA_VERSION_NAME=$(echo "$VERSION" | sed 's/\.0$//')

          echo "JIRA_VERSION_NAME: ${JIRA_VERSION_NAME}"
          echo "JIRA_VERSION_NAME=${JIRA_VERSION_NAME}" >> "$GITHUB_ENV"
          echo "jira-version-name=${JIRA_VERSION_NAME}" >> "$GITHUB_OUTPUT"
