name: Get Jira Version

description: Get jira version from the build number.

outputs:
  JIRA_VERSION:
    description: 'The Jira version derived from the build number.'
    value: ${{ steps.get_version.outputs.JIRA_VERSION }}

runs:
    using: "composite"
    steps:
      - uses: SonarSource/ci-github-actions/get-build-number@7b10475b2a95613850ef1b20a5a7704af69cffd2 # v1.0.1
        if: ${{ !env.BUILD_NUMBER }}
      - name: Get jira version from build number
        id: get_version
        shell: bash
        run: |
          # Extract everything up to the third dot (major.minor.patch)
          VERSION=$(echo "$BUILD_NUMBER" | cut -d '.' -f 1-3)
          
          # Remove trailing '.0' if it exists (to match Jira version format)
          JIRA_VERSION=$(echo "$VERSION" | sed 's/\.0$//')

          echo "JIRA_VERSION: ${JIRA_VERSION}"
          echo "JIRA_VERSION=${JIRA_VERSION}" >> "$GITHUB_ENV"
          echo "JIRA_VERSION=${JIRA_VERSION}" >> "$GITHUB_OUTPUT"
