name: 'Lock Branch'
description: 'Locks or unlocks a branch by modifying the lock_branch setting in branch protection rules.'

inputs:
  branch:
    description: 'The branch name to lock/unlock'
    required: true
  freeze:
    description: 'Set to true to lock (freeze) the branch, false to unlock (unfreeze)'
    required: true
  slack-channel:
    description: 'Optional Slack channel to notify about the state change'
    required: false
  github-token:
    description: 'GitHub token with admin permissions (defaults to Vault)'
    required: false
  slack-token:
    description: 'Slack token for notifications (defaults to Vault)'
    required: false

outputs:
  branch:
    description: 'The branch that was modified'
    value: ${{ steps.run_python_script.outputs.branch }}
  previous-state:
    description: 'The previous lock state of the branch (true/false)'
    value: ${{ steps.run_python_script.outputs.previous_state }}
  current-state:
    description: 'The current lock state of the branch (true/false)'
    value: ${{ steps.run_python_script.outputs.current_state }}

runs:
  using: 'composite'
  steps:
    - name: Get Secrets from Vault
      id: secrets
      if: ${{ !inputs.github-token || (!inputs.slack-token && inputs.slack-channel) }}
      uses: SonarSource/vault-action-wrapper@v3
      with:
        secrets: |
          development/github/token/{REPO_OWNER_NAME_DASH}-lock token | GITHUB_LOCK_TOKEN;
          development/kv/data/slack token | SLACK_TOKEN;

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Lock/Unlock Branch
      id: run_python_script
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token || fromJSON(steps.secrets.outputs.vault).GITHUB_LOCK_TOKEN }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_FREEZE: ${{ inputs.freeze }}
      run: |
        python ${{ github.action_path }}/lock_branch.py \
          --branch "$INPUT_BRANCH" \
          --freeze "$INPUT_FREEZE" \
          --repository "${{ github.repository }}" \
          >> $GITHUB_OUTPUT

    - name: Send Slack Notification
      if: ${{ inputs.slack-channel != '' }}
      shell: bash
      env:
        SLACK_TOKEN: ${{ inputs.slack-token || fromJSON(steps.secrets.outputs.vault).SLACK_TOKEN }}
        INPUT_CHANNEL: ${{ inputs.slack-channel }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_FREEZE: ${{ inputs.freeze }}
      run: |
        python ${{ github.action_path }}/notify_slack.py \
          --channel "$INPUT_CHANNEL" \
          --branch "$INPUT_BRANCH" \
          --repository "${{ github.repository }}" \
          --freeze "$INPUT_FREEZE" \
          --run-url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
