name: Test Release Jira Version Action

on:
  workflow_call:
  pull_request:
    paths:
      - 'release-jira-version/**'
      - '.github/workflows/test-release-jira-version.yml'
  push:
    branches:
      - branch-*
    paths:
      - 'release-jira-version/**'
      - '.github/workflows/test-release-jira-version.yml'
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd release-jira-version
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run unit tests
        run: |
          cd release-jira-version
          python -m pytest test_release_jira_version.py -v --cov=release_jira_version --cov-report=term-missing
