name: Test Release Jira Version Action

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - branch-*
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          cd release-jira-version
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run unit tests
        run: |
          cd release-jira-version
          python -m pytest test_release_jira_version.py -v --cov=release_jira_version --cov-report=term-missing
