name: Test Update Analysis as a Service Action

on:
  workflow_call:
  pull_request:
    paths:
      - 'update-analysis-as-a-service/**'
      - '.github/workflows/automated-release.yml'
      - '.github/workflows/test-update-analysis-as-a-service.yml'
  push:
    branches:
      - master
      - v*
    paths:
      - 'update-analysis-as-a-service/**'
      - '.github/workflows/automated-release.yml'
      - '.github/workflows/test-update-analysis-as-a-service.yml'
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: github-ubuntu-latest-s

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run shell unit tests
        run: bash update-analysis-as-a-service/test_update_libs_versions_toml.sh


